language: php
php:
- 5.6.23
install: composer install
script:
- ./vendor/bin/phing test
after_script:
- ./vendor/bin/coveralls -vvv
notifications:
  email:
    recipients:
    - kristof@2dotstwice.be
    - bram@2dotstwice.be
