language: php
php:
  - 5.5
  - 5.6
install: composer install
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpspec run
notifications:
  email:
    recipients:
      - kristof@2dotstwice.be
      - bram@2dotstwice.be
