language: php
php:
- 5.6.23
- 7.0
- 7.1
install: composer install
script:
- ./vendor/bin/phing test
after_script:
- ./vendor/bin/coveralls -vvv
notifications:
  email:
    recipients:
    - bram@2dotstwice.be
